package com.project.tiaBird.gameObject.geometryObject.item.equipment.qualifiedEquipment.weapon.weaponParameters;

public enum WeaponEquivalent {

        GLOVE, WEAPONLESS,
        DAGGER, PIERCING_DAGGER, SPIKE_GLOVE, LITE_MACE, SICKLE,
        CLUB, HEAVY_MACE, SHORT_LANCE, MORGENSHTERN,
        LONG_SPEAR, STAFF, LANCE,
        LITE_CROSSBOW, DART, SLING, HEAVY_CROSSBOW, THROWING_LANCE,

        LITE_HAMMER, LITE_PICKAX, SHORT_SWORD, KUKRI, THROWING_AXE, HAND_AXE,
        BATTLE_HAMMER, BATTLE_AXE, LONG_SWORD, HEAVY_PICKAX, RAPIER, SCIMITAR, TRIDENT, FLAIL,
        HALBERD, GLAVE, GUISARME, TWO_HANDED_AXE, TWO_HANDED_CLUB, TWO_HANDED_SWORD, PIKE, SCYTHE, RANSEUOOR, HEAVY_FLAIL, YATAGAN,
        SHORT_BOW, COMPOSED_SHORT_BOW, LONG_BOW, COMPOSED_LONG_BOW,

        KAMA, NUNCHAKU, SJANGHEM, SAI,
        DWARF_WAR_AXE, WIP, BROADSWORD,
        ORC_DOUBLE_AXE, GNOME_HOOK_HAMMER, DOUBLE_BLADE_SWORD, MASSACRE_FLAIL, DWARF_URGOSH, SPIKE_FLAIL,
        HAND_CROSSBOW, BOLAS, SHURIKEN, HEAVU_AUTOCROSSBOW, LITE_AUTOCROSSBOW

}
