package com.project.tiaBird.gameObject.geometryObject.creature.character.feat;

public enum FeatEnum {
    ACROBATIC, AGILE, ALERTNESS, ANIMAL_AFFINITY, LIGHT_ARMOR_PROFICIENCY, MEDIUM_ARMOR_PROFICIENCY,
    HEAVY_ARMOR_PROFICIENCY, ATHLETIC, AUGMENT_SUMMONING, BLIND_FIGHT, COMBAT_CASTING, COMBAT_EXPERTISE,
    IMPROVED_DISARM, IMPROVED_FEINT, IMPROVED_TRIP, WHIRLWIND_ATTACK, COMBAT_REFLEXES, DECEITFUL,
    DEFT_HANDS, DILIGENT, DODGE, MOBILITY, SPRING_ATTACK, ENDURANCE, DIEHARD, ESCHEW_MATERIALS,
    EXOTIC_WEAPON_PROFICIENCY, EXTRA_TURNING, GREAT_FORTITUDE, IMPROVED_COUNTERSPELL,
    IMPROVED_CRITICAL, IMPROVED_FAMILIAR, IMPROVED_INITIATIVE, IMPROVED_TURNING, IMPROVED_UNARMED_STRIKE,
    DEFLECT_ARROWS, IMPROVED_GRAPPLE, SNATCH_ARROWS, STUNNING_FIST, INVESTIGATOR, IRON_WILL, LEADERSHIP,
    LIGHTNING_REFLEXES, MAGICAL_APTITUDE, MARTIAL_WEAPON_PROFICIENCY, MOUNTED_COMBAT, MOUNTED_ARCHERY, RIDE_BY_ATTACK,
    SPIRITED_CHARGE, TRAMPLE, NATURAL_SPELL, NEGOTIATOR, NIMBLE_FINGERS, PERSUASIVE, POINT_BLANK_SHOT, FAR_SHOT,
    PRECISE_SHOT, IMPROVED_PRECISE_SHOT, RAPID_SHOT, MANYSHOT, SHOT_ON_THE_RUN, POWER_ATTACK, CLEAVE, GREAT_CLEAVE,
    IMPROVED_BULL_RUSH, IMPROVED_OVERRUN, IMPROVED_SUNDER, QUICK_DRAW, RAPID_RELOAD, RUN, SELF_SUFFICIENT,
    SHIELD_PROFICIENCY, IMPROVED_SHIELD_BASH, TOWER_SHIELD_PROFICIENCY, SIMPLE_WEAPON_PROFICIENCY, SKILL_FOCUS,
    SPELL_FOCUS, GREATER_SPELL_FOCUS, SPELL_MASTERY, SPELL_PENETRATION, GREATER_SPELL_PENETRATION, STEALTHY,
    TOUGHNESS, TRACK, TWO_WEAPON_FIGHTING, TWO_WEAPON_DEFENSE, IMPROVED_TWO_WEAPON_FIGHTING, GREATER_TWO_WEAPON_FIGHTING,
    WEAPON_FINESSE, WEAPON_FOCUS, WEAPON_SPECIALIZATION, GREATER_WEAPON_FOCUS, GREATER_WEAPON_SPECIALIZATION, BREW_POTION,
    CRAFT_MAGIC_ARMS_AND_ARMOR, CRAFT_ROD, CRAFT_STAFF, CRAFT_WAND, CRAFT_WONDROUS_ITEM, FORGE_RING, SCRIBE_SCROLL,
    EMPOWER_SPELL, ENLARGE_SPELL, EXTEND_SPELL, HEIGHTEN_SPELL, MAXIMIZE_SPELL, QUICKEN_SPELL,
    SILENT_SPELL, STILL_SPELL, WIDEN_SPELL
}
